CREATE DATABASE estoque;
USE estoque;
CREATE TABLE produtos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255),
    descricao TEXT,
    quantidade INT,
    preco DECIMAL(10,2)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
INSERT INTO produtos (nome, descricao, quantidade, preco) VALUES
('Jaqueta de Couro', 'Jaqueta de couro fino', 40, 299.99),
('Vestido Floral', 'Vestido estampado com flores', 25, 149.99),
('Calça Jeans Skinny', 'Calça jeans justa e confortável', 35, 79.99),
('Blusa de Tricô', 'Blusa de tricô com padrão de losangos', 50, 39.99),
('Tênis Esportivo', 'Tênis leve e confortável para esportes', 60, 129.99),
('Bolsa de Couro', 'Bolsa de couro com alça ajustável', 30, 199.99),
('Camiseta Básica', 'Camiseta de algodão em cores variadas', 75, 19.99),
('Sapato Social', 'Sapato de couro para ocasiões formais', 20, 179.99),
('Saia Midi Plissada', 'Saia midi plissada em tecido leve', 45, 89.99),
('Casaco de Inverno', 'Casaco quente com forro de lã', 15, 249.99),
('Óculos de Sol', 'Óculos de sol com armação de metal', 55, 59.99),
('Chapéu Fedora', 'Chapéu clássico em feltro', 10, 49.99),
('Mochila Escolar', 'Mochila resistente com compartimentos', 70, 69.99),
('Pulseira de Prata', 'Pulseira delicada em prata 925', 80, 29.99),
('Lenço Estampado', 'Lenço de seda com estampa floral', 40, 34.99),
('Relógio Analógico', 'Relógio com pulseira de couro', 25, 99.99),
('Cinto de Couro', 'Cinto de couro com fivela prateada', 50, 44.99),
('Colete Jeans', 'Colete jeans com detalhes desgastados', 20, 59.99),
('Blazer Slim Fit', 'Blazer ajustado ao corpo em tecido elástico', 30, 149.99),
('Sandália de Salto', 'Sandália elegante com salto alto', 40, 89.99),
('Brincos de Pérola', 'Brincos clássicos em pérola natural', 65, 39.99),
('Camisa Polo', 'Camisa polo em piquet de algodão', 55, 29.99),
('Bermuda Cargo', 'Bermuda casual com bolsos utilitários', 35, 49.99),
('Blusa de Moletom', 'Blusa de moletom com capuz', 25, 54.99),
('Scarpin Preto', 'Scarpin clássico em couro preto', 30, 129.99),
('Carteira de Couro', 'Carteira compacta em couro genuíno', 45, 24.99),
('Anel de Prata', 'Anel com detalhes entrelaçados em prata 925', 60, 49.99),
('Pijama de Algodão', 'Conjunto de pijama confortável em algodão', 20, 39.99),
('Jaqueta Corta-vento', 'Jaqueta leve resistente ao vento', 40, 79.99),
('Legging Fitness', 'Legging para prática de atividades físicas', 30, 34.99),
('Blusa de Alça', 'Blusa de alça em tecido leve', 35, 19.99),
('Relógio Digital', 'Relógio digital com pulseira de silicone', 25, 19.99),
('Regata Esportiva', 'Regata para atividades físicas em tecido respirável', 50, 14.99),
('Sapato Oxford', 'Sapato social com cadarço em couro', 15, 159.99),
('Boné de Baseball', 'Boné clássico com aba curva', 40, 19.99),
('Camisa Xadrez', 'Camisa de flanela em padrão xadrez', 30, 59.99),
('Suéter de Cashmere', 'Suéter macio e luxuoso em cashmere', 10, 299.99),
('Pulseira de Couro', 'Pulseira masculina em couro trançado', 45, 29.99),
('Sapato Casual', 'Sapato casual em couro marrom', 25, 109.99),
('Óculos de Grau', 'Óculos de grau com armação de acetato', 20, 79.99),
('Cachecol de Lã', 'Cachecol macio e quente em lã', 35, 44.99),
('Moletom com Zíper', 'Moletom com zíper e capuz', 30, 64.99),
('Blusa de Manga Longa', 'Blusa de malha com mangas compridas', 40, 24.99),
('Tênis Casual', 'Tênis casual em tecido canvas', 20, 49.99),
('Jaqueta Bomber', 'Jaqueta bomber em tecido leve', 25, 119.99);
